Fix typos and small issues with the tutorial
ESMValGroup/ESMValTool_Tutorial pull request #125
Opened 2020-08-10 15:25 UTC by stefsmeets

# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [ ] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [ ] Give this pull request a descriptive title.
- [ ] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [ ] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [ ] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Hi guys, just creating this pull request to keep track of some small issues I'm running into with the tutorial. It's mostly typos, formatting errors, and some clarifications here and there.

- Closes #123

2020-09-03 14:23 UTC, SarahAlidoost commented on _episodes/02-installation.md
>      you can alternatively try a 32 bit version.
Please replace all of the text before the code block below with "Please download Miniconda3 by running"

2020-09-03 14:34 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +`~/julia` directory or move it there after downloading. To download and extract the file, you can use the following commands:
```suggestion
Next, to download and extract the file `julia-1.0.5-linux-x86_64.tar.gz`, you can use the following commands:
```

2020-09-03 14:35 UTC, SarahAlidoost commented on _episodes/02-installation.md
>  page](https://julialang.org/downloads/). Download the file directly to the
Please remove this paragraph, no need to have three different instructions for downloading the file.

2020-09-03 14:42 UTC, SarahAlidoost commented on _episodes/04-recipe.md
> +> Plots for the dataset(s) are located in `./recipe_example_#_#/diag_timeseries_temperature/timeseries_diag/`
```suggestion
> Plots for the dataset(s) are located in `./recipe_example_#_#/plots/diag_timeseries_temperature/timeseries_diag/`
```

2020-09-03 14:57 UTC, SarahAlidoost commented on _episodes/06-debugging.md
>  > You are assisting a colleague with ESMValTool. The colleague changes the
```suggestion
> You are assisting a colleague with ESMValTool. The colleague replaces the
```

2020-09-03 14:58 UTC, SarahAlidoost commented on _episodes/06-debugging.md
> +> ``datasets/project`` entry to ``CMIP6`` and runs the recipe. However, ESMValTool
```suggestion
> "CMIP5" in ``project: CMIP5`` to ``CMIP6`` and runs the recipe. However, ESMValTool
```

2020-09-03 15:14 UTC, SarahAlidoost commented on _episodes/06-debugging.md
> +Change and run the recipe:
Nice example. However, this section aims to show the difference between the absolute and relative path of the diagnostic script. "creating your own diagnostic" is another episode in the advanced part of the tutorial that would be developed in the near future.

2020-09-03 15:15 UTC, SarahAlidoost commented on _episodes/06-debugging.md
> +42            script: ~/esmvaltool_tutorial/hello.py
```suggestion
42            script: <path_to_esmvaltool>/diag_scripts/ocean/diagnostic_timeseries.py
```

2020-09-03 15:15 UTC, SarahAlidoost commented on _episodes/06-debugging.md
> +
```suggestion
Now examine `./esmvaltool_output/recipe_example_#_#/run/diag_timeseries_temperature/timeseries_diag/` to see if it worked! Of course, this is a simple example, but it shows how you can customize diagnostic scripts or even make your own.

```

2020-09-03 15:17 UTC, SarahAlidoost commented on _episodes/06-debugging.md
> +
"creating your own diagnostic" is another episode in the advanced part of the tutorial that would be developed in the near future. Also, "Available recipe and diagnostic scripts" are already mentioned in the next section.

2020-09-03 15:28 UTC, SarahAlidoost requested changes
@stefsmeets thank you for the improvements. Please see my comments.

2020-09-04 08:20 UTC, stefsmeets commented on _episodes/06-debugging.md
> +Change and run the recipe:
It was the only thing I could get to work with my limited knowledge 3 weeks ago 😅

The absolute path you are referring to here is very deep in miniconda, so I didn't think the instruction was very useful. The path for me is nested somewhere in: `~/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/`. I think it is bad practice to recommend people to go looking around there. What do you think about adding a link to the diag script from the ESMValTool directory and running them from the working directory?

2020-09-04 08:26 UTC, stefsmeets commented
I addressed your comments. There is just one part that I don't find very satisfying. Please have a look at my comment here:
https://github.com/ESMValGroup/ESMValTool_Tutorial/pull/125#discussion_r483464828

I reverted my changes, but I think this part needs some more thought.

2020-09-04 09:15 UTC, SarahAlidoost approved these changes
@stefsmeets thank you.

2020-09-04 09:24 UTC, merged