Add brief summary of possible ways to use ESMValTool
ESMValGroup/ESMValTool_Tutorial pull request #194
Opened 2021-03-16 13:40 UTC by rswamina

# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.
- [x] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [x] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [ ] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes {https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/157}

2021-03-16 13:45 UTC, rswamina commented
@SarahAlidoost - Were you going to add a few lines on downloading the source files and compiling them (not with Github) in the Development mode lesson? Could you do that so I can link to it here and request a review?

2021-03-17 12:28 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +> load the module and start using ESMValTool with the following :
```suggestion
> load the module with the following:
```

2021-03-17 12:34 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +> ```
```suggestion
> ```

After loading ``esmvaltool``, we can start using ESMValTool. Please see the [next lesson]({{ page.root }}{% link _episodes/03-configuration.md %}). 
```

2021-03-17 12:35 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +>
```suggestion
```

2021-03-17 12:39 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +> source installation in the lesson [Development and
```suggestion
> 3) If you would like to start experimenting with existing diagnostics or contributing to ESMvalTool, please see the instructions for 
> source installation in the lesson [Development and
```
```suggestion
> 4) If you would like to start contributing to ESMvalTool, please see the instructions for 
> source installation in the lesson [Development and
```

2021-03-17 12:42 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +> 4) If you would like to start contributing to ESMvalTool, please see the instructions for
```suggestion
> 3) If you would like to start experimenting with existing diagnostics or contributing to ESMvalTool, please see the instructions for 
```

2021-03-17 12:50 UTC, SarahAlidoost requested changes
@rswamina thank you for improving the lesson. I added a few comments. I merged numbers 3 and 4 into one item. Because they only differ on how to get the source code i.e downloading zip file or using git clone. The installation procedure is the same. I will explain this in the episode "development and contribution". 
In addition, I think it is not necessary to have these items in a box. Could you please remove the {: .solution} format and convert these items to normal texts?

2021-03-17 14:04 UTC, rswamina commented
@SarahAlidoost - I can do that and also I want to add a link to the JASMIN module load option. Will notify when I finish and then it should be ready to merge?

2021-03-19 10:47 UTC, rswamina commented
@SarahAlidoost  - Have made the suggested changes and added link to the JASMIN page. This hsould be ok to merge now unless you see something.

2021-03-19 16:05 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +## ESMValTool Installation/Usage  Options - A quick summary
```suggestion
```

2021-03-19 16:10 UTC, SarahAlidoost commented on _episodes/02-installation.md
> + associated software such as GitHub and Conda.
```suggestion
Before we begin, here are all the possible ways in which you can use ESMValTool
depending on your level of expertise or involvement with ESMvalTool and 
associated software such as GitHub and Conda.
```

2021-03-19 16:11 UTC, SarahAlidoost commented on _episodes/02-installation.md
> + as a module, for e.g., the [CEDA JASMIN](https://help.jasmin.ac.uk/article/4955-community-software-esmvaltool)
```suggestion
1. If you have access to a server where ESMValTool is already installed
as a module, for e.g., the [CEDA JASMIN](https://help.jasmin.ac.uk/article/4955-community-software-esmvaltool)
```

2021-03-19 16:14 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +
```suggestion
~~~bash
module load esmvaltool
~~~
After loading ``esmvaltool``, we can start using ESMValTool. Please see the [next lesson]({{ page.root }}{% link _episodes/03-configuration.md %}). 
```

2021-03-19 16:15 UTC, SarahAlidoost commented on _episodes/02-installation.md
> +
```suggestion
2. If you would like to install ESMValTool as a conda package, then this lesson
will tell you how!
3. If you would like to start experimenting with existing diagnostics or contributing to ESMvalTool, please see the instructions for 
source installation in the lesson [Development and
contribution]({{ page.root }}{% link _episodes/08-development-setup.md %}) and
in the [documentation](https://docs.esmvaltool.org/en/latest/quickstart/installation.html).
```

2021-03-19 16:18 UTC, SarahAlidoost commented
> @SarahAlidoost - Have made the suggested changes and added link to the JASMIN page. This hsould be ok to merge now unless you see something.

@rswamina thank you for addressing my comments. I suggested some changes to fix the style. Could you please have a look?

2021-03-24 10:56 UTC, rswamina commented
@SarahAlidoost - I am happy with the changes in formatting. Thanks!

2021-03-24 12:54 UTC, SarahAlidoost commented
> @SarahAlidoost - I am happy with the changes in formatting. Thanks!

Could you please commit the suggestions?

2021-03-24 13:16 UTC, rswamina commented
> > @SarahAlidoost - I am happy with the changes in formatting. Thanks!
> 
> Could you please commit the suggestions?

Done! Anything else?

2021-03-24 13:21 UTC, SarahAlidoost commented
> > > @SarahAlidoost - I am happy with the changes in formatting. Thanks!
> > 
> > 
> > Could you please commit the suggestions?
> 
> Done! Anything else?

Awesome, no.

2021-03-24 13:21 UTC, SarahAlidoost approved these changes

2021-03-24 13:24 UTC, merged