Change link in tutorial from master to main
ESMValGroup/ESMValTool_Tutorial pull request #211
Opened 2021-07-08 07:19 UTC by Peter9192

Because the master branch was renamed to main.

Closes #209

2021-07-08 14:19 UTC, antoine1501 requested changes
I would rather write this link (blob/ rather than raw/)
--> https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/data/dataset.urls
Sorry for the duplication of modification request for this.

2021-07-09 07:31 UTC, Peter9192 commented on setup.md
> +[ds]: https://github.com/ESMValGroup/ESMValTool_Tutorial/raw/main/data/dataset.urls
```suggestion
[ds]: https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/data/dataset.urls
```

2021-07-09 07:32 UTC, Peter9192 commented
> 
> 
> I would rather write this link (blob/ rather than raw/)
> --> https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/data/dataset.urls
> Sorry for the duplication of modification request for this.

Modified. Note that the other one that still has 'raw' needs that, otherwise the download command doesn't work.

2021-07-09 08:11 UTC, antoine1501 approved these changes
Link properly modified

2021-07-09 14:41 UTC, Peter9192 commented
@axel-lauer could you add @antoine1501 to the esmvaltool development team?

2021-07-30 08:35 UTC, Peter9192 commented
@rswamina could you approve the PR so we can merge it?

2021-08-02 10:18 UTC, rswamina approved these changes

2021-08-02 13:56 UTC, merged

2021-08-02 13:56 UTC, Peter9192 commented
Thanks!